export const firstAidClassificationExamples = [
    {text: "What is the first thing you should do when you come across someone who is unconscious?", label: "help"},
    {text: "How do you treat a person who is having a heart attack?", label: "help"},
    {text: "What is the proper technique for performing CPR on an adult?", label: "help"},
    {text: "What should you do if someone is choking?", label: "help"},
    {text: "What are the signs and symptoms of heat stroke?", label: "help"},
    {text: "How can you prevent a nosebleed from happening again?", label: "help"},
    {text: "What is the best way to treat a burn?", label: "help"},
    {text: "What should you do if you suspect someone has a concussion?", label: "help"},
    {text: "How do you treat a sprained ankle?", label: "help"},
    {text: "What should you do if someone has a seizure?", label: "help"},
    {text: "How can you tell if someone is suffering from dehydration?", label: "help"},
    {text: "How can you prevent a cut from getting infected?", label: "help"},
    {text: "What is the best way to treat a bee sting?", label: "help"},
    {text: "How do you treat a broken bone?", label: "help"},
    {text: "What should you do if you suspect someone is experiencing a stroke?", label: "help"},
    {text: "How can you prevent frostbite from happening?", label: "help"},
    {text: "What is the proper way to remove a tick?", label: "help"},
    {text: "What should you do if someone has a head injury?", label: "help"},
    {text: "What are the signs and symptoms of a heart attack in women?", label: "help"},
    {text: "How do you treat a snakebite?", label: "help"},
    {text: "What is the best way to stop bleeding from a wound?", label: "help"},
    {text: "How can you prevent a sunburn from happening?", label: "help"},
    {text: "What should you do if someone has a nosebleed that won't stop?", label: "help"},
    {text: "How do you treat a dislocated joint?", label: "help"},
    {text: "What are the signs and symptoms of a concussion?", label: "help"},
    {text: "How can you prevent hypothermia from happening?", label: "help"},
    {text: "What is the proper way to treat a cut?", label: "help"},
    {text: "What should you do if someone has an allergic reaction?", label: "help"},
    {text: "How do you treat a puncture wound?", label: "help"},
    {text: "What is the best way to prevent a sprain?", label: "help"},
    {text: "How can you tell if someone is having a heart attack?", label: "help"},
    {text: "What should you do if someone is having trouble breathing?", label: "help"},
    {text: "How do you treat a concussion?", label: "help"},
    {text: "What are the signs and symptoms of a broken bone?", label: "help"},
    {text: "How can you prevent a nosebleed?", label: "help"},
    {text: "What is the best way to treat a black eye?", label: "help"},
    {text: "What should you do if someone is having a seizure for the first time?", label: "help"},
    {text: "How do you treat a minor burn?", label: "help"},
    {text: "What are the signs and symptoms of heat exhaustion?", label: "help"},
    {text: "How can you prevent a burn from happening?", label: "help"},
    {text: "What should you do if someone has a dislocated shoulder?", label: "help"},
    {text: "How do you treat a chemical burn?", label: "help"},
    {text: "What are the signs and symptoms of a broken bone?", label: "help"},
    {text: "How can you prevent a nosebleed?", label: "help"},
    {text: "What is the best way to treat a black eye?", label: "help"},
    {text: "What should you do if someone is having a seizure for the first time?", label: "help"},
    {text: "How do you treat a minor burn?", label: "help"},
    {text: "What are the signs and symptoms of heat exhaustion?", label: "help"},
    {text: "How can you prevent a burn from happening?", label: "help"},
];

export const randomQuestionsClassificationExample = [
    {text: "How do plants get energy?", label: "non help"},
    {text: "What is the speed of light?", label: "non help"},
    {text: "Why do we sleep?", label: "non help"},
    {text: "How tall is Mount Everest?", label: "non help"},
    {text: "Can dogs see colors?", label: "non help"},
    {text: "What is photosynthesis?", label: "non help"},
    {text: "Who discovered electricity?", label: "non help"},
    {text: "Why do leaves change color?", label: "non help"},
    {text: "How do airplanes fly?", label: "non help"},
    {text: "Can you hear sound in space?", label: "non help"},
    {text: "Who invented the telephone?", label: "non help"},
    {text: "What is the meaning of life?", label: "non help"},
    {text: "How does the internet work?", label: "non help"},
    {text: "What is the largest mammal in the world?", label: "non help"},
    {text: "Can humans breathe underwater?", label: "non help"},
    {text: "Who painted the Mona Lisa?", label: "non help"},
    {text: "How are stars formed?", label: "non help"},
    {text: "What is a black hole?", label: "non help"},
    {text: "Why do we dream?", label: "non help"},
    {text: "What is the capital of Australia?", label: "non help"},
    {text: "How do earthquakes happen?", label: "non help"},
    {text: "What is the difference between weather and climate?", label: "non help"},
    {text: "Who was the first person to walk on the moon?", label: "non help"},
    {text: "How do birds fly?", label: "non help"},
    {text: "What is the purpose of the human appendix?", label: "non help"},
    {text: "How does the heart work?", label: "non help"},
    {text: "What is the tallest animal in the world?", label: "non help"},
    {text: "Can snakes hear?", label: "non help"},
    {text: "Who discovered penicillin?", label: "non help"},
    {text: "What is the difference between a fruit and a vegetable?", label: "non help"},
    {text: "Why is the sky blue?", label: "non help"},
    {text: "What is the circumference of the earth?", label: "non help"},
    {text: "How do airplanes land?", label: "non help"},
    {text: "Who wrote the play 'Romeo and Juliet'?", label: "non help"},
    {text: "What is the speed of sound?", label: "non help"},
    {text: "How do hurricanes form?", label: "non help"},
    {text: "What is the largest country in the world?", label: "non help"},
    {text: "How does the immune system work?", label: "non help"},
    {text: "What is the boiling point of water?", label: "non help"},
    {text: "What is the meaning of the word 'onomatopoeia'?", label: "non help"},
    {text: "Who invented the light bulb?", label: "non help"},
    {text: "What is the smallest planet in our solar system?", label: "non help"},
    {text: "What is the difference between a lake and a pond?", label: "non help"},
    {text: "How do ants communicate?", label: "non help"},
    {text: "Who wrote the book '1984'?", label: "non help"},
    {text: "What is the meaning of the word 'antidisestablishmentarianism'?", label: "non help"},
    {text: "What is the difference between a hurricane and a typhoon?", label: "non help"},
    {text: "How do tornadoes form?", label: "non help"},
    {text: "Who painted the ceiling of the Sistine Chapel?", label: "non help"},
    {text: "What is the difference between a virus and a bacteria?", label: "non help"},
];